export * from "./tbl_admin";
export * from "./tbl_org";
export * from "./tbl_books";
export * from "./tbl_chapters";
export * from "./tbl_questions";
export * from "./tbl_users";
export * from "./tbl_certificates";
export * from "./tbl_users_progress";
export * from "./tbl_users_question_progress";
